name: Deploy to InfinityFree

on:
  push:
    branches:
      - main # Akan otomatis deploy setiap kali Anda push ke branch main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files to InfinityFree FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/
        exclude: |
          **/.git*
          **/.git*/**
          .github/**
          vercel.json
          README.md
